### ISSUE TITLE
[ROS2 Porting] meeting 2020/10/29

### ISSUE THREAD

**Issue by mitsudome-r** [tier4/AutowareArchitectureProposal.proj#100]
1. Go over action items from the last meeting https://github.com/tier4/AutowareArchitectureProposal/issues/96
   On going action times:
 - [ ] @dejanpan figure out the state of porting for topic_tools package
 - [ ] @dejanpan add CUDA and TensorRT (From tier4/Pilot.Auto#53) dependencies into the https://gitlab.com/autowarefoundation/autoware.auto/AutowareAuto/-/blob/master/.aderc-amd64-foxy
2. Go over current blockers
 - Traffic Light classifier successfully built in local machine, but not in ade. Needs update on ade volume by @dejanpan
 - If you are using opencv, add `<depend>libopencv-dev</depend>` to package.xml
 - CI is not outputting error at test failure
   - Some tests are not passing in ROS1
     - If it is failing in ROS1, remove them from porting.
   - @esteve to modify CI so that it produces error when tests fail
   - @mitsudome-r will look at current test cods and remove or fix them so that CI will pass after @esteve's modification on CI
3. Others:
Can Apex.AI self review the MRs to speed up the reviews a bit? -> Yes
Can we move the meeting time by 1h so it is back at 9AM CET? This will be 5PM in JST
  - @mitsudome-r will reschedule the meeting

**Comment by fred-apex-ai** [comment]
## blockers
  - [PR](https://github.com/tier4/AutowareArchitectureProposal/pull/95) to install osqp only once should really be merged
  - mpc_follower not reviewed yet https://github.com/tier4/Pilot.Auto/pull/52
  - what about open PRs to AutowareArchitectureProposal? https://github.com/tier4/AutowareArchitectureProposal/pull/63, https://github.com/tier4/AutowareArchitectureProposal/pull/83 and https://github.com/tier4/AutowareArchitectureProposal/pull/63 have been dormant for a while

  ## in progress
  - updating porting-doc https://github.com/tier4/AutowareArchitectureProposal/pull/101
  - fix osqp_interface exporting dependencies: had to dig deep and learned a lot about ament_cmake https://github.com/tier4/Pilot.Auto/pull/66
 - wanted to take over https://github.com/tier4/AutowareArchitectureProposal/pull/87 but I don't have the rights to merge
