### ISSUE TITLE
[Post-ROS2-Porting] Require C++ standard strictly

### ISSUE THREAD

**Issue by fred-apex-ai** [tier4/AutowareArchitectureProposal.proj#106]
# Problem

We currently write in a package's `CMakeLists.txt`

```cmake
```cmake
if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 14)
endif()
```

and cmake then invokes `g++ -std=gnu++14`. But we shouldn't allow GNU extensions because it is not portable and with the above, we are not guaranteed we really get C++14, it could also be C++11 as a fallback; see https://crascit.com/2015/03/28/enabling-cxx11-in-cmake/

# Proposed solution

All ported packages should instead use

```cmake
if(NOT CMAKE_CXX_STANDARD)
  set(CMAKE_CXX_STANDARD 14)
  set(CMAKE_CXX_STANDARD_REQUIRED ON)
  set(CMAKE_CXX_EXTENSIONS OFF)
endif()
```

Let us do one big commit that introduces these changes after the initial porting

**Comment by esteve** [comment]
Sounds good to me, but should we defer this for after porting? As part of all the other cleanups, I mean.

**Comment by fred-apex-ai** [comment]
@esteve yes, that's what I had in mind. I updated the issue description accordingly
