### ISSUE TITLE
difference between AutowareArchitectureProposal lidar_apollo_instance_segmentation and Autoware.AI lidar_apollo_cnn_seg_detect

### ISSUE THREAD

**Issue by peterlee909** [tier4/AutowareArchitectureProposal.proj#107]
Is there any difference between AutowareArchitectureProposal lidar_apollo_instance_segmentation and Autoware.AI lidar_apollo_cnn_seg_detect?

In my opinion, the preprocessing and postprocessing of point cloud are the same between two packages.
Is the used model are better in AutowareArchitectureProposal lidar_apollo_instance_segmentation package?

Thanks.

**Comment by yukkysaito** [comment]
lidar_apollo_instance_segmentation includes code refactoring and object orientation estimation.

Also, there are three types of DNN models: velodyne 16, 64, and 128 layers.

**Comment by yunqiushuiman** [comment]
@yukkysaito  Hi, could you please explain why need to add a factor 0.5 to estimate the object orientation like this: " obs->heading = std::atan2(vec_y, vec_x) * 0.5 "  in lidar_apollo_instance_segmentation package?  I am a little confused here, Thank you!
