### ISSUE TITLE
AutowareArquitectureProposal in jetson tx2 and build problem in amd64 laptop

### ISSUE THREAD

**Issue by auronman** [tier4/AutowareArchitectureProposal.proj#130]
HI

It is possible to run this software in a arm64 device like nvidia jetson tx2?

Other question. Im trying to build the software following github instructions. When i reach last 3 packages (143 of 146) my laptop freezes. I dont know why, its like he cant build those last packages. They are related to planning behaviour

Thanks

**Comment by kenji-miyake** [comment]
Thank you for your contributions/questions.
I'll close this according to [our contribution guidelines](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/CONTRIBUTING.md).
