### ISSUE TITLE
[Post ROS2 Porting] Unify usage of tf library

### ISSUE THREAD

**Issue by mitsudome-r** [tier4/AutowareArchitectureProposal.proj#132]
We have packages using different syntax to obtain required tfs (lookupTransform, waitForTransform).
We should look through all the packages and make sure they use same functions for the same purpose.

**Comment by nnmm** [comment]
Besides the two packages above, there is only one usage in pointcloud_preprocessor where I think it makes sense to keep waitForTransform.
