### ISSUE TITLE
[ROS2] setup_ubuntu20.04.sh not working

### ISSUE THREAD

**Issue by hayato-m126** [tier4/AutowareArchitectureProposal.proj#140]
I tried to setup ros2 branch, but I got erros below.

## Error
$ ./setup_ubuntu20.04.sh
...
TASK [autoware : Autoware (install gdown to download some files for neural network)] ***
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to find any of pip2, pip to use.  pip needs to be installed."}
...

$ colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release --catkin-skip-building-tests
colcon: Command not found

## why
- Python2 pip is not installed.
- Colcon is not installed with ros2 binary.

ref: https://qiita.com/tamusou1/items/ef6035f3f6e098c8bb98#colcon-command-not-found

## solution
- use pip3 in ansible
- install colcon in ansbile

**Comment by TakaHoribe** [comment]
solved by https://github.com/tier4/AutowareArchitectureProposal/pull/142.
