### ISSUE TITLE
Error in building system monitor

### ISSUE THREAD

**Issue by azamshoaib** [tier4/AutowareArchitectureProposal.proj#155]
Hi, I got the following error upon building the traffic_light_classifier
 error: ‘nvmlClocksThrottleReasonDisplayClockSetting’ was not declared in this scope
                                  : ((X)&nvmlClocksThrottleReasonDisplayClockSetting) 

Kindly help me in this regard.

**Comment by taichiH** [comment]
Could you please share me your developing environment?

**Comment by ghost** [comment]
@ayberksener Hi there. Could you confirm if this issue is still occuring with the latest v0.9.1 branch code please?

**Comment by ghost** [comment]
Closing issue due to lack of response from OP. @ayberksener If this issue is still occuring, then please provide more information about your development environment so that we can assist further.
