### ISSUE TITLE
DoorStatus.msg does not exist

### ISSUE THREAD

**Issue by ngsford** [tier4/AutowareArchitectureProposal.proj#163]
awapi/autoware_api_msgs/msg/DoorStatus.msg'
  does not exist.  Message: message file not found

Call Stack (most recent call first):
  /opt/ros/melodic/share/genmsg/cmake/genmsg-extras.cmake:113 (assert_file_exists)
  CMakeLists.txt:13 (add_message_files)

**Comment by turtleMaster20** [comment]
I built it with the branch v0.5.1, can you try that out?
