### ISSUE TITLE
parking osm map

### ISSUE THREAD

**Issue by zqw-hooper** [tier4/AutowareArchitectureProposal.proj#171]
hello,  i can not find parking osm map in  sample map , can you provide this map ? very thanks

**Comment by zerolover** [comment]
https://drive.google.com/open?id=197kgRfSomZzaSbRrjWTx614le2qN-oxx

**Comment by ghost** [comment]
@zqw-hooper Hi there. Could you confirm if you were able to use the map in the link above to test out planning for parking?

**Comment by zerolover** [comment]
@LalithVipulananthan Sure~
