### ISSUE TITLE
AutowareArchitectureProposal with CARLA simulator

### ISSUE THREAD

**Issue by Vin1291** [tier4/AutowareArchitectureProposal.proj#198]
Hi all,

Has anyone tried connecting the AutowareArchitectureProposal with CARLA? 

If yes, can you please help me with it? Any kind of help will be appreciated. Thank you!

**Comment by yukkysaito** [comment]
We are actively connecting with LGSVL, but haven't heard of CARLA yet

**Comment by athulg** [comment]
Is there any update on this? It would be really helpful if a bridge to Carla can be created

**Comment by kenji-miyake** [comment]
Thank you for your contributions/questions.
I'll close this according to [our contribution guidelines](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/CONTRIBUTING.md).
