### ISSUE TITLE
Camera_optical_link TF

### ISSUE THREAD

**Issue by arudomanenko** [tier4/AutowareArchitectureProposal.proj#204]
Hi. Thanks for a great work! I am trying to run traffic light detection and some thing not so obvious for me. For example: where can I get camera_optical_link tf? I see that the calibration_manage in autoware load this data from file and publish it. But it does not make sense how functional like this realized it AutowareArchitectureProposal. I found some clue in usb_cam (like camera_fame_id parameter), but it doesn't help me.

**Comment by yukkysaito** [comment]
Thanks for using it. optical_link is automatically generated from urdf.
(In ros, the camera coordinate system is camera_link and the image coordinate system is camera_optical_link.)
https://github.com/tier4/sensor_description.iv.universe/blob/master/camera_description/urdf/monocular_camera.xacro#L42

I'm not sure, what is calibration_manage?
