### ISSUE TITLE
Failed to load nodelet.

### ISSUE THREAD

**Issue by nisailhan** [tier4/AutowareArchitectureProposal.proj#207]
Hi everyone, 

When I launch the preprocessing launch file, I get this error as you can see below. 
My system and package configuration:
Operating System & Version Ubuntu 18.04.5 LTS
ROS Version: Melodic
Kernel Version: 5.11.0-051100-generic
Architecture: x86-64
Firmware Version: E16V3IMS.104
PCL Version: 1.8
CMake Version: 3.10.2
Boost Version:  1.65.1.0ubuntu1
OpenCV Version: 3.2.03.3.9
Eigen Version: 3.3.9

Is anyone have an idea? 

[ERROR] [1628492487.509749716]: Failed to load nodelet [/pointcloud_preprocessor/crop_box_filter_mesurement_range] of type [pointcloud_preprocessor/src/crop_box_filter_nodelet] even after refreshing the cache: According to the loaded plugin descriptions the class pointcloud_preprocessor/src/crop_box_filter_nodelet with base class type nodelet::Nodelet does not exist. Declared types are  depth_image_proc/convert_metric depth_image_proc/crop_foremost depth_image_proc/disparity depth_image_proc/point_cloud_xyz depth_image_proc/point_cloud_xyz_radial depth_image_proc/point_cloud_xyzi depth_image_proc/point_cloud_xyzi_radial depth_image_proc/point_cloud_xyzrgb depth_image_proc/register gscam/GSCamNodelet image_proc/crop_decimate image_proc/crop_nonZero image_proc/crop_non_zero image_proc/debayer image_proc/rectify image_proc/resize image_publisher/image_publisher image_rotate/image_rotate image_view/disparity image_view/image imu_filter_madgwick/ImuFilterNodelet jsk_topic_tools/Block jsk_topic_tools/DeprecatedRelay jsk_topic_tools/HzMeasure jsk_topic_tools/LightweightThrottle jsk_topic_tools/MUX jsk_topic_tools/Passthrough jsk_topic_tools/Relay jsk_topic_tools/Snapshot jsk_topic_tools/StealthRelay jsk_topic_tools/StringRelay jsk_topic_tools/SynchronizedThrottle jsk_topic_tools/VitalCheckerNodelet jsk_topic_tools_test/LogUtils nodelet_tutorial_math/Plus pcl/BAGReader pcl/BoundaryEstimation pcl/ConvexHull2D pcl/CropBox pcl/EuclideanClusterExtraction pcl/ExtractIndices pcl/ExtractPolygonalPrismData pcl/FPFHEstimation pcl/FPFHEstimationOMP pcl/MomentInvariantsEstimation pcl/MovingLeastSquares pcl/NodeletDEMUX pcl/NodeletMUX pcl/NormalEstimation pcl/NormalEstimationOMP pcl/NormalEstimationTBB pcl/PCDReader pcl/PCDWriter pcl/PFHEstimation pcl/PassThrough pcl/PointCloudConcatenateDataSynchronizer pcl/PointCloudConcatenateFieldsSynchronizer pcl/PrincipalCurvaturesEstimation pcl/ProjectInliers pcl/RadiusOutlierRemoval pcl/SACSegmentation pcl/SACSegmentationFromNormals pcl/SHOTEstimation pcl/SHOTEstimationOMP pcl/SegmentDifferences pcl/StatisticalOutlierRemoval pcl/VFHEstimation pcl/VoxelGrid stereo_image_proc/disparity stereo_image_proc/point_cloud2 uvc_camera/CameraNodelet uvc_camera/StereoNodelet velodyne_driver/DriverNodelet velodyne_laserscan/LaserScanNodelet velodyne_pointcloud/CloudNodelet velodyne_pointcloud/RingColorsNodelet velodyne_pointcloud/TransformNodelet
[ERROR] [1628492487.509776842]: The error before refreshing the cache was: According to the loaded plugin descriptions the class pointcloud_preprocessor/src/crop_box_filter_nodelet with base class type nodelet::Nodelet does not exist. Declared types are  depth_image_proc/convert_metric depth_image_proc/crop_foremost depth_image_proc/disparity depth_image_proc/point_cloud_xyz depth_image_proc/point_cloud_xyz_radial depth_image_proc/point_cloud_xyzi depth_image_proc/point_cloud_xyzi_radial depth_image_proc/point_cloud_xyzrgb depth_image_proc/register gscam/GSCamNodelet image_proc/crop_decimate image_proc/crop_nonZero image_proc/crop_non_zero image_proc/debayer image_proc/rectify image_proc/resize image_publisher/image_publisher image_rotate/image_rotate image_view/disparity image_view/image imu_filter_madgwick/ImuFilterNodelet jsk_topic_tools/Block jsk_topic_tools/DeprecatedRelay jsk_topic_tools/HzMeasure jsk_topic_tools/LightweightThrottle jsk_topic_tools/MUX jsk_topic_tools/Passthrough jsk_topic_tools/Relay jsk_topic_tools/Snapshot jsk_topic_tools/StealthRelay jsk_topic_tools/StringRelay jsk_topic_tools/SynchronizedThrottle jsk_topic_tools/VitalCheckerNodelet jsk_topic_tools_test/LogUtils nodelet_tutorial_math/Plus pcl/BAGReader pcl/BoundaryEstimation pcl/ConvexHull2D pcl/CropBox pcl/EuclideanClusterExtraction pcl/ExtractIndices pcl/ExtractPolygonalPrismData pcl/FPFHEstimation pcl/FPFHEstimationOMP pcl/MomentInvariantsEstimation pcl/MovingLeastSquares pcl/NodeletDEMUX pcl/NodeletMUX pcl/NormalEstimation pcl/NormalEstimationOMP pcl/NormalEstimationTBB pcl/PCDReader pcl/PCDWriter pcl/PFHEstimation pcl/PassThrough pcl/PointCloudConcatenateDataSynchronizer pcl/PointCloudConcatenateFieldsSynchronizer pcl/PrincipalCurvaturesEstimation pcl/ProjectInliers pcl/RadiusOutlierRemoval pcl/SACSegmentation pcl/SACSegmentationFromNormals pcl/SHOTEstimation pcl/SHOTEstimationOMP pcl/SegmentDifferences pcl/StatisticalOutlierRemoval pcl/VFHEstimation pcl/VoxelGrid stereo_image_proc/disparity stereo_image_proc/point_cloud2 uvc_camera/CameraNodelet uvc_camera/StereoNodelet velodyne_driver/DriverNodelet velodyne_laserscan/LaserScanNodelet velodyne_pointcloud/CloudNodelet velodyne_pointcloud/RingColorsNodelet velodyne_pointcloud/TransformNodelet
[FATAL] [1628492487.509923061]: Failed to load nodelet '/pointcloud_preprocessor/crop_box_filter_mesurement_range` of type `pointcloud_preprocessor/src/crop_box_filter_nodelet` to manager `pcl_manager'
[pointcloud_preprocessor/crop_box_filter_mesurement_range-2] process has died [pid 12463, exit code 255, cmd /opt/ros/melodic/lib/nodelet/nodelet load pointcloud_preprocessor/src/crop_box_filter_nodelet pcl_manager ~input:=/points_raw ~output:=/points_raw/cropbox/filtered __name:=crop_box_filter_mesurement_range __log:=/home/nisa/.ros/log/795ddd4a-f8d9-11eb-8acf-000ec6840533/pointcloud_preprocessor-crop_box_filter_mesurement_range-2.log].
log file: /home/nisa/.ros/log/795ddd4a-f8d9-11eb-8acf-000ec6840533/pointcloud_preprocessor-crop_box_filter_mesurement_range-2*.log

**Comment by kenji-miyake** [comment]
Thank you for your contributions/questions.
I'll close this according to [our contribution guidelines](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/CONTRIBUTING.md).
