### ISSUE TITLE
How to visualize Camera-Lidar fusion detection?

### ISSUE THREAD

**Issue by AthulGangadharan** [tier4/AutowareArchitectureProposal.proj#209]
Hello, I'm trying to understand how the camera-lidar fusion based detected objects can be viewed in Rviz? Is there a single "Image" topic to visualize them? Thanks!

**Comment by kenji-miyake** [comment]
Thank you for your contributions/questions.
I'll close this according to [our contribution guidelines](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/CONTRIBUTING.md).
