### ISSUE TITLE
ERROR : Cannot locate rosdep definition for [autoware_simulation_msgs]

### ISSUE THREAD

**Issue by tuan97anton** [tier4/AutowareArchitectureProposal.proj#216]
I install AutowareArchitectureProposal branch ros2, when I run to command : `./setup_ubuntu20.04.sh`
I get error : `Cannot locate rosdep definition for [autoware_simulation_msgs]`
But I don't find pkg for `autoware_simulation_msgs` .

**Comment by kenji-miyake** [comment]
Thank you for your question.
Please read [our contribution guidelines](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/CONTRIBUTING.md).

`ros2` branch isn't used anymore, please use `main` instead.
