### ISSUE TITLE
use sim time in the project

### ISSUE THREAD

**Issue by JackRen88** [tier4/AutowareArchitectureProposal.proj#223]
Hello,everyone
How to easily modify the use sim time in the launch file? For example ,I use this project in simulation, need to set use_sim_time to true,however,modifying the launch file one by one is more troublesome and troublesome.

**Comment by kenji-miyake** [comment]
Thank you for your question.
Please read [our contribution guidelines](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/CONTRIBUTING.md).

Please refer to https://github.com/tier4/AutowareArchitectureProposal_launcher/blob/dfbed2be4155b5cdee04e27f7103608cfd79f494/autoware_launch/launch/logging_simulator.launch.xml#L25. It uses `SetParameter` to set `use_sim_time=true` globally.
