### ISSUE TITLE
Question about release timeline.

### ISSUE THREAD

**Issue by hengjiUSTC** [tier4/AutowareArchitectureProposal.proj#228]
I found the latest release tag 0.11 is pushed around 7 month ago, but the main branch is been updated pretty actively. Do you still planning to release new tags in a specific frequency?

**Comment by kenji-miyake** [comment]
We're sorry, but we don't release a new tag for this repository since it's just a proposal.

Instead, we're working on integrating this to AWF's repository. Please wait for that.
https://discourse.ros.org/t/technical-steering-committee-tsc-meeting-36-2021-11-17-minutes/23168/1
