### ISSUE TITLE
Setup failed with error

### ISSUE THREAD

**Issue by ajay1606** [tier4/AutowareArchitectureProposal.proj#229]
Hello,
Thanks to Tier4, for sharing this ROS2 version repository.
I have tested versions up to v0.9.1 of AutowareArchitectureProposal.IV and everything work well as mentioned in the document.

But with v0.11.1 (ROS2), I faced a few issues to test this repository, any help is much appreciated. 
1. git checkout ros2, the command doesn't work as there is no branch name 'ros2', alternatively which branch should we checkout to test in ROS2 version.
2. For instance, i have did checkout with v0.11.1 but it failed to run ./setup_ubuntu_20.04.sh script.

![image](https://user-images.githubusercontent.com/29722843/147201571-ab07fba8-3daa-4622-ad79-8738ffe7f6d6.png)

Have tried, rosdep update and apt update, but nothing fixed this issue. 

Looking forward to listening from you. 

**Working platform:**
Ubuntu Version: 20.04
Ros Verison: Foxy

**Comment by kenji-miyake** [comment]
Thank you for your question, but please read [our contribution guidelines](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/CONTRIBUTING.md).

Since we're working on https://github.com/autowarefoundation/autoware, please wait for that.
