### ISSUE TITLE
source code problem

### ISSUE THREAD

**Issue by schweinebauch** [tier4/AutowareArchitectureProposal.proj#231]
hello
In this repo, I can not find any source  code about algorithms, should I install this project so that I can read source code?

thanks

**Comment by kenji-miyake** [comment]
Thank you for your question, but please read [our contribution guidelines](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/CONTRIBUTING.md).

The repositories that have the source code are listed [here](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/autoware.proj.repos).
