### ISSUE TITLE
is it suppored ros2 foxy rosbag file?

### ISSUE THREAD

**Issue by lejk8104** [tier4/AutowareArchitectureProposal.proj#238]
hello, i use Autoware Architecture Proposal 0.11.0 release version

I following this tutorial **Installation steps** but I think "rosbag" file is not release foxy

can I download ros2 foxy rosbag file?
![Screenshot from 2022-04-04 16-56-59](https://user-images.githubusercontent.com/41908895/161499696-f88f8a62-02e4-44eb-8028-0ccceeff01e8.png)
![Screenshot from 2022-04-04 16-56-51](https://user-images.githubusercontent.com/41908895/161499702-43d8abaa-71e2-4140-9719-1a3155efe69a.png)

thanks

**Comment by kenji-miyake** [comment]
Thank you for your question.

Since we've moved to Autoware Core/Universe, this repository is unfortunately no longer supported.
Could you read this README instead?
https://github.com/autowarefoundation#welcome-to-the-autoware-foundation-
