### ISSUE TITLE
run error camera_lidar_fusion_based_detection.launch

### ISSUE THREAD

**Issue by Gironote** [tier4/AutowareArchitectureProposal.proj#29]
step1) source devel/setup.bash
step2) roslaunch autoware_launch autoware.launch map_path:=/home/kaai/AutowareArchitectureProposal
step3) rosbag play --clock camera_lidar_fusion.bag -r 0.2

![Screenshot from 2020-06-03 22-56-51](https://user-images.githubusercontent.com/65701965/83645506-8971f300-a5ed-11ea-8fa3-30943e0c588b.png)

<Here's where we failed>
step4) we didn't know the package name so we guessed the package name and tested. 
 $ roslaunch camera_lidar_fusion_based_detection camera_lidar_fusion_based_detection.launch
 $ roslaunch camera_lidar_fusion_based_detection_launch camera_lidar_fusion_based_detection.launch
like this....

how to run 
[AutowareArchitectureProposal/src/launcher/perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch] file?
And, 
[AutowareArchitectureProposal/src/launcher/autoware_launch/launch/autoware.launch] file..?

**Comment by yukkysaito** [comment]
sorry for late.
If it's only detection, just camera_lidar_fusion_based_detection.launch will work.
Pls, check following things.
- Is the topic connected correctly?
- Is tf published between lidar to camera?
- Is the camera_info correct? (calibrated?)
- Is this parameter set correctly?https://github.com/tier4/AutowareArchitectureProposal/blob/master/src/launcher/perception_launch/launch/object_recognition/detection/camera_lidar_fusion_based_detection.launch#L4-L21

**Comment by Gironote** [comment]
Do I just  play  rosbag  and  type "camera_lidar_fusion_based_detection.launch
"in other terminer???

Shouldn't we write the package name together to execute launch file??


2020년 6월 10일 (수) 오후 10:39, Yukihiro Saito <notifications@github.com>님이 작성:

**Comment by yukkysaito** [comment]
>Do I just  play  rosbag  and  type "camera_lidar_fusion_based_detection.launch
"in other terminer???

Yes.

Have you ever touched ROS?
You may need some ros knowledge to apply this system in your environment.
http://wiki.ros.org/ROS/Tutorials
