### ISSUE TITLE
Traffic Light Fine Detection: any special requirements?

### ISSUE THREAD

**Issue by sergiev** [tier4/AutowareArchitectureProposal.proj#45]
Hi, I'm using cuda10.2 with tensorRT 7.1.3 to run the traffic_light_fine_detection module. But no matter what, I'm keeping getting the error on this line of code:
```
  CUDA_CHECK(cudaMemcpyAsync(
    mTrtCudaBuffer[inputIndex], inputData, mTrtBindBufferSize[inputIndex], cudaMemcpyHostToDevice,
    mTrtCudaStream));
```
it's from lib/src/TrtNet.cpp, [lines 241-243](https://github.com/tier4/AutowareArchitectureProposal/blob/8657215190d8485deb618882dca5f89ffccf2f2c/src/perception/traffic_light_recognition/traffic_light_fine_detector/lib/src/TrtNet.cpp#L241).
Here's how the error looks like:
![Screenshot from 2020-06-26 17-04-30](https://user-images.githubusercontent.com/27900857/85865876-3a277880-b7cf-11ea-8771-d97d6710241d.png)
* In the first debug line we display the size of input trafficlightroi array.
* In the second line there are coordinates (in order xMin, yMin, xMax, yMax) of rough ROI obtained from map data. 
* Then there are some checks that we're passing exact stages in code. inputData lines shows that we've passed the prepareImage function correctly
* inference stages are about going through particular lines in net_ptr_->doInference.
Here's whole doInference function with its' uncomplicated debug output:
![Screenshot from 2020-06-26 17-09-59](https://user-images.githubusercontent.com/27900857/85866624-57107b80-b7d0-11ea-9de0-d1037543d997.png)
 
I'll be happy to solve this issue on my own, but my knowledge of CUDA so far limited to capability of swap the cudaMemcpyAsync to cudaMemcpy with respect to documentation. As you may guess, it didn't help :(

**Comment by taichiH** [comment]
I’m sorry, It’s our mistake. we’ve attached a wrong download link. we will fix this as soon as possible.

**Comment by taichiH** [comment]
@sergiev 
we've fixed the link, please check!
Since this is an architecture proposal version repository (less test), I think the bugs are still somewhere, so please let us know if you find the bugs.

**Comment by sergiev** [comment]
well, it works
thank you so much, @taichiH

**Comment by persuelx** [comment]
you have solved the problem?@sergiev
