### ISSUE TITLE
AutowareArchitectureProposal with LG simulator 

### ISSUE THREAD

**Issue by ajay1606** [tier4/AutowareArchitectureProposal.proj#50]
Hello everyone,

Has anyone tried connecting the AutowareArchitectureProposal version with LG simulator?

**Comment by yukkysaito** [comment]
Sorry for the delay.
We've tried to connect internally, but it will take a bit of time with some improvements on the LG simulator. 
e.g. lidar data model, sensor latency, vehicle controller, etc.

**Comment by ajay1606** [comment]
@yukkysaito Thanks for your response, We will wait for the updated version of LG simulator.

**Comment by yuasabe** [comment]
Hello, are there any updates here in regards to connecting this version of Autoware with LGSVL?

**Comment by kenji-miyake** [comment]
Thank you for your contributions/questions.
I'll close this according to [our contribution guidelines](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/CONTRIBUTING.md).
