### ISSUE TITLE
obstacle_avoidance_planner

### ISSUE THREAD

**Issue by lucianzhong** [tier4/AutowareArchitectureProposal.proj#53]
Can someone explain the codes or the design  architecture of obstacle_avoidance_planner in planning/scenario_planning/lane_driving/motion_planning

About the obstacle_avoidance_planner, I only find the reference paper:"A convex optimization approach to smooth trajectories for motion planning with car-like robots"

**Comment by k0suke-murakami** [comment]
The main design is: 
1. Make a costmap.
2. Make constraints for reference points based on the costmap.
3. Smoothing reference points by using elastic band, which is from the paper you referred to.

Hope this is helpful for you.

**Comment by lucianzhong** [comment]
@k0suke-murakami 
Thanks for the replay. 
The obstacle_avoidance_planner node has optimized position but not the speed the profile. The car can only stop if there is a a moving obstacle. I not should if I am right or not. Please correct me, if I am wrong.

**Comment by lucianzhong** [comment]
@k0suke-murakami
Thanks for the replay.
The obstacle_avoidance_planner node has optimized path but not the speed the profile. The car can only stop if there is a a moving obstacle. I not should if I am right or not. Please correct me, if I am wrong.

**Comment by lucianzhong** [comment]
@k0suke-murakami
Thanks for the replay.
The obstacle_avoidance_planner node has optimized path but not the speed profile. The car can only stop if there is a moving obstacle. I not should if I am right or not. Please correct me, if I am wrong.

**Comment by k0suke-murakami** [comment]
> The obstacle_avoidance_planner node has optimized path but not the speed profile. 

Yes.

The car stop when an "obstacle" is detected on the trajectory. `obstacle_stop_planner`  node is responsible for this function.

**Comment by lucianzhong** [comment]
@k0suke-murakami
Thanks a lot for the replay.

**Comment by lucianzhong** [comment]
@k0suke-murakami
Hey, Murakami, in your github respositories, there are qp_planner, eb_planner. I am wondering these planners are developed for AutowareArchitectureProposal or not?

**Comment by k0suke-murakami** [comment]
> I am wondering these planners are developed for AutowareArchitectureProposal or not?


No, and I would say AutowareArchitectureProposal has a better implementation.
