### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by vehxianfish** [tier4/AutowareArchitectureProposal.proj#55]
when I install cuda,the error occurs:
```
TASK [cuda : CUDA (install CUDA 10.2)] *****************************************     
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to update apt cache."}       
	to retry, use: --limit @/home/AutowareArchitectureProposal/ansible/localhost-setup-ubuntu18.04-devpc.retry  

PLAY RECAP *********************************************************************     
localhost                  : ok=3    changed=0    unreachable=0    failed=1       

Complete      
```

**Comment by wep21** [comment]
Can you execute `sudo apt update` and try again?
Ansible apt module sometimes fails its task.

**Comment by ghost** [comment]
@vehxianfish Could you confirm if you were able to resolve this issue, or if any further assistance is required? :slightly_smiling_face:

**Comment by 0-0-07** [comment]
> @vehxianfish Could you confirm if you were able to resolve this issue, or if any further assistance is required? 🙂

please help me :) @LalithVipulananthan #75
