### ISSUE TITLE
Localization with real vehcile data

### ISSUE THREAD

**Issue by ajay1606** [tier4/AutowareArchitectureProposal.proj#56]
Localization with real vehicle data tested, pose, and twist estimation working good with the low input rate (-r 0.2). but it fails with the original input rate. In case of failure, Which part of the process taking a long time?

Regards,
Ajay

**Comment by ajay1606** [comment]
@yukkysaito  could you please comment on this

**Comment by yukkysaito** [comment]
@ajay1606 sorry for late reply. Is it localizationn fail?
Could you please give us a rosbag or video if possible?

**Comment by ajay1606** [comment]
@yukkysaito Thanks for your response, Issue has been solved. We are currently using single LiDAR , but the current sensing module configured to 3 Lidar, we have to skip few preprocessing steps. After that its working well. And, we understood that, Lidar distortion removal algorithm currently supported for only 16 and 32 channel lidar, Not for 64 ?

**Comment by ghost** [comment]
@ajay1606 So that we can better respond to your query, could you confirm if there is any specific documentation or statement from a developer that says that the distortion correction preprocessor is only supported for 16 and 32 channel LiDAR sensors?

**Comment by ajay1606** [comment]
@LalithVipulananthan Thanks for your response, We noticed that the current version of AAP includes few modifications in the Velodyne driver package also. In the file, func.cc (sensing/driver/velodyne/velodyne_pointcloud/src/conversions) it is mentioned that node is debugged only for VLP16 and VLP32C, So is it only for calibrating lidar or including interpolating points ?

**Comment by ghost** [comment]
> So is it only for calibrating lidar or including interpolating points ?

It is for interpolation, scan cutting, and pre-filtering. If those functions are required, then only VLP16, VLP-32C, and VLS-128 LiDARs are supported. VLP16 and VLP-32C have been thoroughly tested, and VLS-128 has been tested so far as confirming that the appropriate topic (`velodyne_points_invalid_near`) and points are published. 

Going back to the original issue of localization failing at the original input rate, the processing for interpolation/distortion correction adds extra data to the PointCloud messages and thus the messages are "heavier" than those created by the stock VLS driver.

**Comment by ajay1606** [comment]
@LalithVipulananthan Thanks for your response. got it
