### ISSUE TITLE
CMAKE error with CUBLAS_LIBRARIES

### ISSUE THREAD

**Issue by ajay1606** [tier4/AutowareArchitectureProposal.proj#57]
Hello ,

I am getting error with fresh installation of Autoware Proposal Architecture, as below please could anyone help me to fix this.

Getting error message after running command;
catkin build --cmake-args -DCMAKE_BUILD_TYPE=Release

Error Message:
![Screenshot from 2020-09-04 09-54-19](https://user-images.githubusercontent.com/29722843/92187652-57468a80-ee95-11ea-9a96-6e1076f18284.png)

![Screenshot from 2020-09-04 09-54-57](https://user-images.githubusercontent.com/29722843/92187662-5e6d9880-ee95-11ea-8331-c67d636fc233.png)

Log file error message:
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CUBLAS_LIBRARIES  linked by target "tensorrt_apollo_cnn_lib" in directory /home/ajay/AutowareArchitectureProposal/src/perception/object_recognition/detection/lidar_apollo_instance_segmentation

Environment:
Ubuntu 18.04
ROS: Melodic
Cmake: 3.18.1

Could you please suggest me, Am i missing something ?

**Comment by yukke42** [comment]
I got the same error, now I can build successfully.

In my case, I changed 
```
find_library(CUBLAS_LIBRARIES cublas HINTS
  ${CUDA_TOOLKIT_ROOT_DIR}/lib)
```
to
```
find_library(CUBLAS_LIBRARIES cublas HINTS
  ${CUDA_TOOLKIT_ROOT_DIR}/lib64)
```
for the four files.
- src/perception/object_recognition/detection/lidar_apollo_instance_segmentation/CMakeLists.txt
- src/perception/object_recognition/detection/tensorrt_yolo3/CMakeLists.txt
- src/perception/traffic_light_recognition/traffic_light_classifier/CMakeLists.txt
- src/perception/traffic_light_recognition/traffic_light_fine_detector/CMakeLists.txt

In my environment, there is no directory `/usr/local/cuda/lib`.
```
$ ls /usr/local/cuda/lib
ls: cannot access '/usr/local/cuda/lib': No such file or directory
$ echo $LD_LIBRARY_PATH
/opt/ros/melodic/lib:/usr/local/cuda/lib64:
```

**Comment by ajay1606** [comment]
@yukke42 Thank you so much

**Comment by ghost** [comment]
@ajay1606 Thank you for reporting this issue and thank you @yukke42 for providing an initial workaround. The relevant CMakeLists files have been updated and so this issue should no longer occur.
