### ISSUE TITLE
can used in edge devices

### ISSUE THREAD

**Issue by yantaixu0120** [tier4/AutowareArchitectureProposal.proj#59]
Hello!
Can this Proposal be used in edge devices such as NVIDIA Jetson series?

**Comment by yukkysaito** [comment]
![Ebe34AeU0AUXYSf](https://user-images.githubusercontent.com/8327598/94759896-1f6f2c00-03dc-11eb-9783-0b65b335f4f4.jpeg)
As for the six cameras for object detection, We run Yolo v3 on the Jetson AGX (industrial).
And We use Nuvo for the main PC and visualization/logging, respectively.
