### ISSUE TITLE
Software Problem

### ISSUE THREAD

**Issue by ivypeng1234** [tier4/AutowareArchitectureProposal.proj#61]
Hello! Can I use it with Ubuntu 20.04 and CUDA 11.0? I tried, but I just can't install ROS on my PC with Ubuntu 20.04.

**Comment by yukkysaito** [comment]
We haven't tried it yet.
Support for ubuntu 20.04 will be provided as ROS2.0

**Comment by 0-0-07** [comment]
> We haven't tried it yet.
> Support for ubuntu 20.04 will be provided as ROS2.0

@yukkysaito  Hello，excuse me， if you have time, can you help me? Many thanks #75
