### ISSUE TITLE
How to fuse camera object detection and lidar seg output pre shape estimation?

### ISSUE THREAD

**Issue by LiyouZhou** [tier4/AutowareArchitectureProposal.proj#64]
https://github.com/tier4/AutowareArchitectureProposal/blob/master/design/Perception/ObjectRecognition/Detection/Detection.md

Assumption:
- Camera object detection output bounding boxes
- Lidar segmentation detection outputs point clusters

I think we need to put shape estimation before fusing in the pipeline. Otherwise, how would you fuse point clusters with a 2d bounding box?

**Comment by kenji-miyake** [comment]
Thank you for your contributions/questions.
I'll close this according to [our contribution guidelines](https://github.com/tier4/AutowareArchitectureProposal.proj/blob/main/CONTRIBUTING.md).
