### ISSUE TITLE
[ROS2 Porting] Meeting Minutes 2020-10-06

### ISSUE THREAD

**Issue by mitsudome-r** [tier4/AutowareArchitectureProposal.proj#65]
1. Short intro
    - Ryohsuke Mitsudome
    - Simon Thompson
    - Takamasa Horibe
    - Jilada Eccleston
    - Esteve Fernandez
    - Nithilan

    - Dejan
    - Frederik Beaujean
    - Nicolai Morin
    - Yunus Caliskan
2. R/K presents the https://github.com/tier4/AutowareArchitectureProposal
3. R/K list the packages which we should port in until Oct 12
    1. https://docs.google.com/spreadsheets/d/1ciUa8EfghRNW-xTHcbbHFtGPwxCU8peBUv-OP_72Ca8/edit?usp=sharing
4. Communication
    1. where to ask questions about https://github.com/tier4/AutowareArchitectureProposal
        1. respective repositories
    2. where to report bugs and features
        1. respective repositories
    3. where to communicate about everything else (meetings cancellation)
        1. use slack
        1. emails via a mailing list for important notice that needs a record
    4. Meeting minutes
        1. https://github.com/tier4/AutowareArchitectureProposal/issues
    5. Work planning (who ports which package by when)
        1. https://docs.google.com/spreadsheets/d/1ciUa8EfghRNW-xTHcbbHFtGPwxCU8peBUv-OP_72Ca8/edit?usp=sharing
5. Apex.AI ports 1 example package
    1. Frederik & Nikolai try porting a package and give a report tomorrow
    1. This will be first done in dashing
6. Apex.AI prepares ade for ROS 2 Foxy & github
    1. https://gitlab.com/ApexAI/ade-cli/-/merge_requests/47
7. R presents CI
    1. https://github.com/tier4/autoware.iv.universe/blob/ros2/.github/workflows/build_and_test.yml
    2. https://github.com/tier4/autoware.iv.universe/pull/2
    3. Present how to install ROS 2 Foxy with plain docker
        1. WIP. Announce in slack channel when its ready
        1. https://docs.google.com/document/d/1eqkWCKHZfHcaY4uvs1eSrIBPU6AZCkyxJI3XoRU1WeU/edit
8. Branch name ros2
9. MRs to be done into the github projects listed in https://github.com/tier4/AutowareArchitectureProposal/blob/master/autoware.proj.repos
10. MRs will be reviewed by 5 Prometheus engineers (Simon, Ryohsuke, Jillada, Esteve, Taka)

11. How many packages
    1. Approximately 80-90 packages
12. Meeting time
    1. Mondays and Thursdays 4pm JST (9am CEST)
13. Porting Guideline
    1. Dejan will post on this issue

**Comment by dejanpan** [comment]
For vcs tool, the documentation: https://github.com/dirk-thomas/vcstool

**Comment by dejanpan** [comment]
## Meeting minutes
1. Run the clang formatter
1. Use the spreadsheet to assign the packages to the developers
1. CI issues to be reported to @mitsudome-r 
1. @esteve and @jpsamper will create the `ade` for ROS 2 Foxy & Github
1.

**Comment by dejanpan** [comment]
@simon-t4 a porting guide: https://index.ros.org/doc/ros2/Contributing/Migration-Guide/

**Comment by nnmm** [comment]
For reference, the GitHub usernames of the five reviewers are: mitsudome-r, esteve, simon-t4, jilaada, TakaHoribe 
The usernames of Apex.AI contributors are nnmm, fred-apex-ai, cvasfi
