### ISSUE TITLE
osqp vendor added twice

### ISSUE THREAD

**Issue by fred-apex-ai** [tier4/AutowareArchitectureProposal.proj#89]
I am not able to build following the instructions in this document:
```sh
dejan.pangercic@ade:~/AutowareArchitectureProposal (ros2 % u=)$ colcon build
[0.415s] ERROR:colcon:colcon build: Duplicate package names not supported:
- osqp_vendor:
  - src/autoware/pilot.auto/vendor/osqp_vendor
  - src/vendor/osqp
```

Edit: I was able to fix above with: `touch src/vendor/osqp/COLCON_IGNORE`.

_Originally posted by @dejanpan in https://github.com/tier4/AutowareArchitectureProposal/pull/87#issuecomment-712962096_

**Comment by esteve** [comment]
Fixed in #95
